version: "3"

services:
  dev:
    build: 
      context: .
      dockerfile: ./config/dev/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/concours
    env_file:
      - .env
    networks:
      - concours-network
    depends_on:
      - mongodb
    command: npm run start:dev
  
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - concoursmongodata:/data/db
    restart: always
    networks:
      - concours-network

networks:
  concours-network:
    driver: bridge

volumes:
  concoursmongodata:

